#!/usr/bin/env python

import os
from huggingface_hub import hf_hub_download

# Directory to store weights
CACHE_DIR = "checkpoints"
os.makedirs(CACHE_DIR, exist_ok=True)

# Download model checkpoint
hf_hub_download(repo_id="apple/DepthPro", filename="depth_pro_model.ckpt", local_dir=CACHE_DIR)
